console.log('Hello Winc Academy');
console.log('Hello ivana');
console.log(4 + 4);
console.log(2 + 9);
console.log(6 - 3);
console.log(5 * 6);
console.log(8 / 2);
console.log(10 % 2);
console.log(typeof 33);
console.log(typeof "33");
